# Generated by Django 5.0.6 on 2024-06-01 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True,
                default=datetime.datetime(
                    2024, 6, 1, 3, 41, 45, 608901, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="total_time_spent",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
