# Generated by Django 5.0.6 on 2024-05-31 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('round', models.CharField(choices=[('qualifying', 'Qualifying'), ('quarter-final', 'Quarter-Final'), ('semi-final', 'Semi-Final'), ('final', 'Final')], max_length=20)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_games', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_games', to='teams.team')),
            ],
        ),
    ]
