# Generated by Django 5.0.6 on 2024-05-31 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                ("login_id", models.AutoField(primary_key=True, serialize=False)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
